var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
var activateLoadingMask,ajaxMainContent,anchorHashFragmentIntercept,anchorIntercept,aspectRatioImgEdits,calledCommonVariables,camelCaseToKebobCase,checkTrustedTypesSupport,closeDrawerOnAnchorClick,commonEventListeners,commonRoutines,commonRoutinesOnFirstLoadOnly,commonRoutinesOnFirstLoadOrAjax,commonVariables,conditionallyReplaceJpgExtensionWithWebpExtension,consoleLog,consoleLogMsgObj,customizePushAndReplaceState,deactivateLoadingMask,deleteCachesUnregisterServiceWorkerAndClearSessionStorage,editExternalLinks,
escapeForwardSlashes,escapeSingleQuotes,fetchAppendToUploadStatusDiv,fetchReject,fetchResolve,fetchResolveWithOptions,fetchResponse,fireCustomEvent,fiveRandomAlphaNumerics,highlightMenuItem,inEu,initializeHeaderHeightAndObserver,initializePopstateLocationChangeListeners,initializeWindowOnResizeRoutines,inner,isObject,isSafari,kebobCaseToCamelCase,loadLocalResource,loadPageDependencies,makeTransparentMaskClickable,maxWidth759px,noTitle,popstateListener,promiseLoader,removeVisibilityHiddenFromTmbAlert,
returnAjaxObject,returnTimeStamp,revealHashedContent,reviseMetaData,reviseSchema,scrollDownByHeaderHeight,serviceWorkerRoutine,setCanonicalLink,setOrRemoveMobileClasses,setOrientation,setMaxWidth759px,siteWideLoader,stripHtmlTags,tmbTT,updateFenestra,updateUriInfo,windowEvents;activateLoadingMask=function(){document.querySelectorAll(".loading-mask").forEach(function(a){a.classList.add("active")})};
ajaxMainContent=function(a,b,c,d){var e;var g=this;if(void 0===b)var f=g.baseHref;else f=b.replace(/\/$/,""),f.includes("?")||(f+="/");-1!==f.indexOf("#")&&(f=f.substring(0,f.indexOf("#")));var l=f+"main.php";null===a&&(a=".");b=function(h){window.setTimeout(function(){function n(p,w){p&&p.parentNode&&(p.parentNode.removeChild(p),p=null,tmbTT.active&&(w=g.DOMPurify.sanitize(w)),x=document.createRange().createContextualFragment(w),document.querySelectorAll("HEADER").forEach(function(y){y.after(x)}))}
window.sessionStorage&&window.sessionStorage.setItem(l,h);if("mouseover"!==d){var m=document.querySelector("main");var q=h.indexOf("<custom-style class=display-none>");var v=h.indexOf("</custom-style>");var r=h.slice(q+33,v);v=h.slice(0,q)+h.slice(v+15);var u=v.indexOf("data-page=");q=v.indexOf(" ",u);q=v.slice(u+10,q);if(g.nonce){var t=!0;(u=document.querySelector(".custom-style"))&&u.dataset&&u.dataset.page&&q&&q===u.dataset.page&&(t=!1);if(t){document.querySelectorAll(".custom-style").forEach(function(p){p.parentNode&&
p.parentNode.removeChild(p)});u=document.querySelector("HEAD");var x=document.createDocumentFragment();t=document.createElement("STYLE");x.appendChild(t);t.setAttribute("nonce",g.nonce);t.setAttribute("class","custom-style");t.setAttribute("data-page",q);t.innerHTML=tmbTT.active?g.DOMPurify.sanitize(r):r;u.appendChild(x);t.removeAttribute("nonce")}}n(m,v);g.appendToCSS(":root","{ --main-opacity: 1; }");m={};r=document.querySelector("main");m.title=r&&r.dataset&&r.dataset.title?r.dataset.title:"Untitled";
m.url=f;document.title=m.title;setCanonicalLink(f);document.querySelectorAll("#header-nav ul a").forEach(function(p){if(p.getAttribute("href")!==a&&p.classList.contains("selected")){p.classList.remove("selected");var w;null==(w=p.closest(".secondary-ul"))||w.classList.remove("selected")}});document.activeElement.blur();!1===c&&window.history.pushState(m,m.title,m.url);""===window.location.hash&&window.scroll(0,0);!0===c&&a&&"#"===a.charAt(0)&&(r=document.querySelector(a),null!==r&&(r.scrollIntoView(),
""===window.location.hash&&g.scrollDownByHeaderHeight()));g.commonRoutinesOnFirstLoadOrAjax();g.deactivateLoadingMask()}},0)};var k=!0===g.metaDataWebpSupport?{webp:"true"}:{webp:"false"};"mouseover"===d?g.mouseoverLoadedURLs&&!g.mouseoverLoadedURLs.includes(l)&&window.sessionStorage&&null===window.sessionStorage.getItem(l)&&(g.ajax.post(l,k,b,!0),g.mouseoverLoadedURLs.push(l)):(window.sessionStorage&&(e=window.sessionStorage.getItem(l)),e?b(e):g.ajax.post(l,k,b,!0))};
anchorHashFragmentIntercept=function(){var a=this;var b=function(c){function d(e){e.preventDefault();if(e=e.target.closest("a"))a.fenestra.location.hash=e.getAttribute("href")}document.querySelectorAll(a.escapeForwardSlashes(c)).forEach(function(e){e.classList.contains("reassign-href-on-anchor-click-listener")||(e.classList.add("reassign-href-on-anchor-click-listener"),e.addEventListener("click",d,!1))})};b('a[href*="#"]:not([href*="//"])');b("a.hash-anchor");document.querySelectorAll("#main-content").forEach(function(c){c.setAttribute("tabIndex",
"0")})};
anchorIntercept=function(){var a;var b=this;var c=function(d){var e;"mouseover"!==d.type&&(b.appendToCSS(":root","{ --main-opacity: 0; }"),b.activateLoadingMask(),b.updateUriInfo());if("A"===d.target.tagName){var g=d.target.getAttribute("href");var f=d.target.href}else(e=d.target.closest("A"))&&e.classList.contains("image-anchor")&&(g=e.getAttribute("href"),f=e.href);if(null===g||void 0===g)g="/";null!==f&&void 0!==f||document.querySelectorAll("BASE").forEach(function(l){l.hasAttribute("href")&&(f=
l.getAttribute("href"))});if(navigator.onLine)if(g&&"#"!==g.charAt(0)){d.preventDefault();if("mouseover"===d.type&&window.sessionStorage.hasOwnProperty(f+"main.php"))return!0;b.ajaxMainContent(g,f,!1,d.type)}else return!0;else return!0};document.querySelectorAll(b.escapeForwardSlashes('a:not([href*="//"]):not([href*="#"]):not(.hash-anchor):not(.gwt-Anchor)')).forEach(function(d){d.classList.contains("anchor-intercept-click-listener")||(d.classList.add("anchor-intercept-click-listener"),d.addEventListener("click",
c));window.sessionStorage&&!d.matches(".site-map a")&&(a=!1,b.siteData.noMouseoverPreload&&b.siteData.noMouseoverPreload.forEach(function(e){d.href.endsWith(e)&&(a=!1)}),a&&!d.classList.contains("anchor-mouseover-listener")&&(d.classList.add("anchor-mouseover-listener"),d.addEventListener("mouseover",c)))})};
aspectRatioImgEdits=function(a,b){var c=this;a.querySelectorAll(c.escapeForwardSlashes(b)).forEach(function(d){if(d.dataset.aspectWidth)var e=d.dataset.aspectWidth;else e=1,console.log("ERROR: aspectWidth not found in dataset of element.",d);if(d.dataset.aspectHeight)var g=d.dataset.aspectHeight;else g=1,console.log("ERROR: aspectHeight not found in dataset of element.",d);(d=d.closest(".aspect-ratio"))&&d.classList.add("ratio-"+e+"x"+g);c.appendToCSS(".ratio-"+e+"x"+g,"{ --aspect-ratio-w: "+e+"; --aspect-ratio-h: "+
g+"; }")})};calledCommonVariables=!1;camelCaseToKebobCase=function(a){return a.replace(/([a-zA-Z])(?=[A-Z])/g,"$1-").toLowerCase()};
checkTrustedTypesSupport=function(){var a=(a=document.querySelector("meta[name=web_author]"))&&a.dataset&&a.dataset.useTrustedTypes&&"true"===a.dataset.useTrustedTypes;window.hasOwnProperty("trustedTypes")&&a?(this.tmbTT.policy=window.trustedTypes.createPolicy("stop-gap",{createHTML:function(b){return b},createScript:function(b){return b},createScriptURL:function(b){return b}}),this.tmbTT.active=!0,this.tmbTT.trusted="",this.tmbTT.untrusted=""):this.tmbTT.active=!1};
closeDrawerOnAnchorClick=function(){function a(){!0===window.matchMedia("(max-width: 759px)").matches&&window.setTimeout(function(){document.querySelectorAll("#hamburger").forEach(function(b){b.click()})},1E3)}document.querySelectorAll(".nav a.internal-anchor").forEach(function(b){b.classList.contains("drawer-internal-anchor-click-listener")||(b.classList.add("drawer-internal-anchor-click-listener"),b.addEventListener("click",a))})};inEu=!1;
commonRoutines=function(){var a=this;var b=function(){window.setTimeout(function(){var c;window.dataLayer=window.dataLayer||[];a.commonRoutinesOnFirstLoadOnly();window.removeEventListener("innerFunctionFinished",b);window.requestAnimationFrame(function(){document.body.focus()});void 0!==navigator.serviceWorker&&(navigator.serviceWorker.controller?console.log("Service Worker active.\n(Hard refresh for new Service Worker.)"):a.useServiceWorker&&a.serviceWorkerRoutine());var d=function(h){var n=document.querySelector("BODY");
var m=document.createDocumentFragment();var q=document.createElement("SCRIPT");m.appendChild(q);q.setAttribute("src",h);q.setAttribute("defer","");n.appendChild(m)};a.gtag=function(){window.dataLayer.push(arguments)};var e=function(){tmbTT.untrusted="https://www.googletagmanager.com/gtag/js?id="+a.siteData.uaString;tmbTT.active?(tmbTT.trusted=tmbTT.policy.createScriptURL(tmbTT.untrusted),d(tmbTT.trusted)):d(tmbTT.untrusted);a.gtag("js",new Date);c={anonymize_ip:!0,cookie_flags:"SameSite=None; Secure",
page_path:window.location.pathname};a.gtag("config",a.siteData.uaString,c);a.googleAnalyticsInitialized=!0};var g=document.body.hasAttribute("data-admin");var f=a.metaNameWebAuthor&&a.metaNameWebAuthor.dataset&&a.metaNameWebAuthor.dataset.chromeLighthouse;var l=a.siteData&&a.siteData.liveSiteUrl&&window.location.origin===a.siteData.liveSiteUrl;var k=function(h){if(!h.ok)throw h={url:h.url,statusText:h.statusText,status:h.status},h;return h};!g&&!f&&l&&navigator.onLine&&!a.googleAnalyticsInitialized&&
a.metaNameWebAuthor&&a.metaNameWebAuthor.dataset&&a.metaNameWebAuthor.dataset.clientIp&&(g=a.metaNameWebAuthor.dataset.clientIp,f=!0,a.hasOwnProperty("siteData")&&a.siteData.hasOwnProperty("excludedIps")&&a.siteData.excludedIps.includes(g)&&(f=!1),f&&(a.inEu=!0,fetch("https://ipapi.co/"+g+"/json").then(k).then(function(h){return h.json()}).then(function(h){h.error?console.log(h):a.inEu=h.in_eu}).catch(function(h){a.inEu=h}).finally(function(){!0===a.inEu?console.log("EU IP detected: no analytics performed"):
(console.log("Initialize analytics"),e())})));a.deactivateLoadingMask()},0)};window.addEventListener("innerFunctionFinished",b);a.checkTrustedTypesSupport();a.commonRoutinesOnFirstLoadOrAjax()};
commonRoutinesOnFirstLoadOnly=function(){var a=this;a.makeTransparentMaskClickable();a.closeDrawerOnAnchorClick();a.noTitle(".footer .no-title");a.initializeWindowOnResizeRoutines();a.popstateListener();""!==a.fenestra.location.hash&&(a.useSpa||!a.useSpa&&2===window.history.length)&&a.scrollDownByHeaderHeight();a.firstLoad=!1;a.appendToCSS(":root","{ --main-opacity: 1; }");a.appendToCSS(":root","{ --footer-opacity: 1; }");window.addEventListener("http404",function(){a.ajaxMainContent("error-404/",
a.baseHref+"error-404/main.php",!0,"click")});document.querySelectorAll("#hamburger").forEach(function(b){b.classList.contains("hamburger-change-listener")||(b.classList.add("hamburger-change-listener"),b.addEventListener("change",function(){b.checked?a.appendToCSS(":root","{ --secondary-ul-position: fixed; }"):window.setTimeout(function(){a.appendToCSS(":root","{ --secondary-ul-position: absolute; }")},280)}))});a.initializeHeaderHeightAndObserver()};
commonRoutinesOnFirstLoadOrAjax=function(){var a=this;window.setTimeout(function(){document.querySelectorAll("main").forEach(function(b){a.previousPageName=a.pageName;a.pageName=b.getAttribute("data-page");a.pageName?a.pageNameCamelCase=kebobCaseToCamelCase(a.pageName):(console.log("ERROR: MAIN element needs page name"),a.pageName="dummy",a.pageNameCamelCase="dummy");void 0===a.loadedDependencies[a.pageName]&&(a.loadedDependencies[a.pageName]=!1)});a.hasOwnProperty("siteData")&&a.siteData.hasOwnProperty("pageDependencies")&&
a.loadPageDependencies()},0)};
commonEventListeners=function(){var a;var b=this;var c=function(e){e.ctrlKey&&e.altKey&&"s"===e.key&&(console.log("Ctrl+Alt+s: Delete caches, unregister service worker, clear session storage"),b.deleteCachesUnregisterServiceWorkerAndClearSessionStorage());e.ctrlKey&&e.altKey&&"l"===e.key&&(console.log("Ctrl+Alt+l: Go to login"),location.replace(b.baseHref+"login"))};var d=function(){var e;document.querySelectorAll(".secondary-ul.selected").forEach(function(f){f.querySelectorAll("a.selected").forEach(function(l){e=l.parentElement.dataset.page})});
var g=!1;a=document.querySelector("MAIN");e&&a.classList.contains(e)&&(g=!0);document.querySelectorAll("[id^=side-switcher]").forEach(function(f){f.checked=!1;g&&f.parentElement.querySelector("#"+f.id+" ~ .secondary-ul.selected")&&(f.checked=!0)})};document.addEventListener("keydown",function(e){"Tab"===e.code&&document.body.classList.add("show-focus-outlines")});document.addEventListener("click",function(e){document.body.classList.remove("show-focus-outlines")});!1===b.windowEvents.keydown&&(window.addEventListener("keydown",
c),b.windowEvents.keydown=!0);document.querySelectorAll("label[for=hamburger]").forEach(function(e){e.classList.contains("label-for-hamburger-click-listener")||(e.classList.add("label-for-hamburger-click-listener"),e.addEventListener("click",d))});document.querySelectorAll("#skip-to-main-content").forEach(function(e){var g=window.location.href;"#main-content"!==g.slice(g.length-13)&&e.setAttribute("href",window.location.href+"#main-content");e.classList.contains("skip-to-main-content-keyup-listener")||
(e.classList.add("skip-to-main-content-keyup-listener"),e.addEventListener("keyup",function(f){f.preventDefault();"Enter"===f.code&&document.querySelectorAll("#main-content").forEach(function(l){l.focus();document.getElementById("hamburger").checked=!1})}))});document.querySelectorAll("label[for=hamburger]:not(.keyup-listener)").forEach(function(e){e.classList.add("keyup-listener");e.addEventListener("keyup",function(g){"Enter"===g.code&&(g.preventDefault(),b.maxWidth759px&&(document.querySelectorAll(".header .menu-side-one").forEach(function(f){f.tabIndex=
0}),document.querySelectorAll(".header .menu-side-two").forEach(function(f){f.tabIndex=-1})),document.querySelectorAll("#hamburger").forEach(function(f){f.click()}))})});document.querySelectorAll(".menu-side-one").forEach(function(e){e.classList.contains("keyup-listener")||(e.classList.add("keyup-listener"),e.addEventListener("keyup",function(g){g.target.classList.contains("menu-side-two")||(g.preventDefault(),"Tab"===g.code&&b.maxWidth759px&&(document.querySelectorAll("#hamburger").forEach(function(f){f.checked=
!0}),document.querySelectorAll("[id^=side-switcher]").forEach(function(f){f.checked=!1})),"Escape"===g.code&&(document.querySelectorAll("#hamburger").forEach(function(f){f.click()}),document.querySelector("body").focus()),"Enter"===g.code&&("A"===e.firstElementChild.tagName?e.firstElementChild.click():e.firstElementChild.id.startsWith("side-switcher")&&(e.firstElementChild.checked=!e.firstElementChild.checked,document.querySelectorAll('.header .nav li[data-span="'+e.firstElementChild.dataset.switcherTarget+
'"]').forEach(function(f){g.target.blur();f.click();f.focus()}),document.querySelectorAll(".header .nav ul li[tabindex]").forEach(function(f){f.tabIndex=0===f.tabIndex?-1:0}))))}))});document.querySelectorAll(".menu-side-two").forEach(function(e){e.classList.contains("keyup-listener")||(e.classList.add("keyup-listener"),e.addEventListener("keyup",function(g){g.target.classList.contains("menu-side-one")||(g.preventDefault(),"Tab"===g.code&&b.maxWidth759px&&(document.querySelectorAll("#hamburger").forEach(function(f){f.checked=
!0}),document.querySelectorAll("[id^=side-switcher]").forEach(function(f){f.checked=!0})),"Escape"===g.code&&(document.querySelectorAll("#hamburger").forEach(function(f){f.click()}),document.querySelector("body").focus()),"Enter"===g.code&&("A"===e.firstElementChild.tagName?e.firstElementChild.click():e.firstElementChild.matches("div[data-for^=side-switcher]")&&(document.querySelectorAll("[id^=side-switcher]").forEach(function(f){f.checked=!f.checked}),document.querySelectorAll('.header .nav li[data-span="'+
e.firstElementChild.dataset.switcherTarget+'"]').forEach(function(f){g.target.blur();f.click();f.focus()}),document.querySelectorAll(".header .nav ul li[tabindex]").forEach(function(f){f.tabIndex=0===f.tabIndex?-1:0}))))}))});document.querySelectorAll("div[data-for^=side-switcher]").forEach(function(e){e.classList.contains(e.dataset.for+"-click-listener")||(e.classList.add(e.dataset.for+"-click-listener"),e.addEventListener("click",function(g){document.querySelectorAll("#"+e.dataset.for).forEach(function(f){f.click()})}));
e.classList.contains(e.dataset.for+"-keyup-listener")||(e.classList.add(e.dataset.for+"-keyup-listener"),e.addEventListener("keyup",function(g){"Enter"===g.code&&(b.maxWidth759px&&(document.querySelectorAll(".header .menu-side-one").forEach(function(f){f.tabIndex=0===f.tabIndex?-1:0}),document.querySelectorAll(".header .menu-side-two").forEach(function(f){f.tabIndex=0===f.tabIndex?-1:0})),document.querySelectorAll("[id^=side-switcher]").forEach(function(f){f.click()}))}))});navigator.onLine&&b.useSpa&&
b.anchorIntercept()};
commonVariables=function(){var a=this;a.calledCommonVariables=!0;a.ajax=a.returnAjaxObject();document.querySelectorAll("base").forEach(function(b){a.baseHref=b.getAttribute("href")});a.customEvent=[];a.lazyloadDefaultOffsetPercent="80%";a.metaNameWebAuthor&&a.metaNameWebAuthor.dataset&&(a.metaDataRootDir=a.metaNameWebAuthor.dataset.rootDir?a.metaNameWebAuthor.dataset.rootDir:"/",a.metaDataWebpSupport=a.metaNameWebAuthor.dataset.webpSupport?"true"===a.metaNameWebAuthor.dataset.webpSupport:!1,a.metaDataUseSpa=
a.metaNameWebAuthor.dataset.useSpa?"true"===a.metaNameWebAuthor.dataset.useSpa:!0,a.metaDataUseServiceWorker=a.metaNameWebAuthor.dataset.useServiceWorker?"true"===a.metaNameWebAuthor.dataset.useServiceWorker:!0);a.useSpa=a.metaDataUseSpa;a.safari=a.isSafari();!0===a.safari||!1===a.metaDataUseServiceWorker?(a.useServiceWorker=!1,!0===a.safari&&console.log("Safari detected."),a.deleteCachesUnregisterServiceWorkerAndClearSessionStorage()):a.useServiceWorker=!0};
consoleLog=function(a){this.logToConsole&&console.log(a)};conditionallyReplaceJpgExtensionWithWebpExtension=function(a,b){this.metaDataWebpSupport&&a.querySelectorAll(this.escapeForwardSlashes(b)).forEach(function(c){c.href.endsWith(".jpg")&&(c.href=c.href.replace(".jpg",".webp"))})};consoleLogMsgObj=function(a,b){this.logToConsole&&console.log(a,b)};
customizePushAndReplaceState=function(){window.history.pushState=function(a){return function(){var b=a.apply(this,arguments);window.dispatchEvent(new Event("pushState"));window.dispatchEvent(new Event("locationchange"));return b}}(window.history.pushState);window.history.replaceState=function(a){return function(){var b=a.apply(this,arguments);window.dispatchEvent(new Event("replaceState"));window.dispatchEvent(new Event("locationchange"));return b}}(window.history.replaceState)};
deactivateLoadingMask=function(){var a,b;var c=this;document.querySelectorAll(".loading-mask.active").forEach(function(d){b=new MutationObserver(function(e){c.appendToCSS(":root","{ --custom-style-elements-opacity: 1; }");b.disconnect()});a={attributes:!0};b.observe(d,a);d.classList.remove("active")})};
deleteCachesUnregisterServiceWorkerAndClearSessionStorage=function(){console.log("Deleting caches, unregistering Service Worker, clearing session storage");window.caches&&window.caches.keys().then(function(a){Object.keys(a||{}).forEach(function(b){window.caches.delete(a[parseInt(b,10)])})}).catch(function(a){console.log("Caches deletion warning: ",a)});void 0!==navigator.serviceWorker&&navigator.serviceWorker.getRegistrations().then(function(a){Object.keys(a||{}).forEach(function(b){a[parseInt(b,
10)].unregister()})}).catch(function(a){console.log("Service Worker de-registration failed: ",a)});window.sessionStorage&&window.sessionStorage.clear()};editExternalLinks=function(a,b,c,d){!0===d&&(d="(opens in new window/tab)");a.querySelectorAll(this.escapeForwardSlashes(b)).forEach(function(e){e.setAttribute("target","_blank");e.setAttribute("rel","noopener noreferrer");c&&e.setAttribute("title",d)})};removeVisibilityHiddenFromTmbAlert=function(){document.querySelectorAll(".tmb-alert.visibility-hidden").forEach(function(a){a.classList.remove("visibility-hidden")})};
escapeSingleQuotes=function(a){return a.replace(/'/g,"\\'")};escapeForwardSlashes=function(a){return a.replace(/\//g,"\\/")};fetchAppendToUploadStatusDiv=function(a){var b=document.createDocumentFragment();var c=document.createElement("P");b.appendChild(c);c.innerHTML=tmbTT.active?this.DOMPurify.sanitize(a):a;this.fetchUploadStatusDiv.appendChild(b)};
fetchReject=function(a){var b=this;b.fetchNoProblem=!1;b.fetchProgressLine&&b.fetchProgressLine.classList.remove("active");return a.then?a.then(function(c){b.consoleLog(c.message);b.fetchAppendToUploadStatusDiv(c.message)}):null};fetchResolve=function(a,b,c){this.consoleLogMsgObj("Success: ",a);this.consoleLog("");this.consoleLog(c);this.fetchAppendToUploadStatusDiv(c);return""!==b?fetch(b):null};
fetchResolveWithOptions=function(a,b,c,d){this.consoleLogMsgObj("Success: ",a);this.consoleLog("");this.consoleLog(d);this.fetchAppendToUploadStatusDiv(d);return""!==b?fetch(b,c):null};fetchResponse=function(a){return 200!==a.status?Promise.reject(a.json()):a.json()};fireCustomEvent=function(a){this.customEvent[a]=new Event(a);window.dispatchEvent(this.customEvent[a])};fiveRandomAlphaNumerics=function(){return(Math.random().toString(36)+"00000000000000000").slice(2,7)};
highlightMenuItem=function(){var a;var b=this.fenestra.location.origin+this.fenestra.location.pathname;"/"!==b.slice(-1)&&"#"!==b.slice(-1)&&(b+="/");document.querySelectorAll(".secondary-ul").forEach(function(c){c.classList.remove("selected")});document.querySelectorAll("header ul li a").forEach(function(c){a=c.href;"/"!==a.slice(-1)&&(a+="/");if(a===b){c.classList.add("selected");var d;null==(d=c.closest(".secondary-ul"))||d.classList.add("selected")}});document.querySelector(".secondary-ul.selected")?
document.querySelector(".primary-ul").classList.remove("selected"):document.querySelector(".primary-ul").classList.add("selected");document.querySelectorAll("div[data-for^=side-switcher] span").forEach(function(c){c.classList.remove("selected")})};initializeHeaderHeightAndObserver=function(){var a=this;a.headerHeight=0;(new ResizeObserver(function(b){b=b[0].contentRect.height;a.headerHeight!==b&&(a.headerHeight=b,a.appendToCSS(":root","{ --header-height: "+a.headerHeight+"px; }"))})).observe(document.querySelector(".header"))};
initializePopstateLocationChangeListeners=function(){var a=this;a.customizePushAndReplaceState();var b=function(){window.dispatchEvent(new Event("locationchange"));window.dispatchEvent(new Event("hashchange"))};!1===a.windowEvents.popstate&&(window.addEventListener("popstate",b,!1),a.windowEvents.popstate=!0);a.updateFenestra();window.addEventListener("locationchange",function(){a.updateFenestra()})};
initializeWindowOnResizeRoutines=function(){var a,b;var c=this;var d=c.debounce(function(){window.matchMedia("(min-width: 760px)").matches&&document.querySelectorAll("#hamburger").forEach(function(e){e.checked=!1});b=c.isMobile;c.isMobile=navigator.userAgentData?navigator.userAgentData.mobile:/iPhone|iPad|iPod|Android/i.test(navigator.userAgent);a=!c.isMobile;b&&a&&(console.log("Switching from mobile view to desktop view"),window.location.reload())},250,!1);!1===c.windowEvents.resize2&&(window.addEventListener("resize",
d,!0),c.windowEvents.resize2=!0)};
inner=function(){var a=this;a.setMaxWidth759px();a.setOrRemoveMobileClasses();a.siteWideLoader();document.querySelectorAll("link[rel=preload][as=script]").forEach(function(b,c,d){b.parentNode.removeChild(b)});!1===a.calledCommonVariables&&a.commonVariables();a.highlightMenuItem();a.editExternalLinks(document,'.main a:not(.social-icon-anchor):not(.saatchi-link):not(.internal-anchor)[href*="//"]',!0,!0);a.editExternalLinks(document,'.main a[class*="social-icon-anchor"][href*="//"]',!0,"Share on social media (opens in new window/tab)");
a.editExternalLinks(document,'.footer a[href*="//"]',!1,!0);a.reviseMetaData(a.siteData.metaData);a.hasOwnProperty(a.pageNameCamelCase)&&a[a.pageNameCamelCase].main();a.updateUriInfo();a.anchorHashFragmentIntercept();a.commonEventListeners();document.querySelectorAll("#skip-to-main-content").forEach(function(b){b.setAttribute("href",window.location.origin+window.location.pathname+"#main-content")});window.setTimeout(function(){a.appendToCSS(":root","{ --background-color-500ms-ease--border-bottom-color-500ms-ease: background-color 500ms ease, border-bottom-color 500ms ease; }");
a.appendToCSS(":root","{ --background-color-500ms-ease--border-bottom-color-500ms-ease--color-500ms-ease: background-color 500ms ease, border-bottom-color 500ms ease, color 500ms ease; }");a.appendToCSS(":root","{ --header-li-not-first-child-a-transition: border-color 0.5s ease, background 0.5s ease; }");a.appendToCSS(":root","{ --opacity-500ms-ease: opacity 500ms ease; }");a.appendToCSS(":root","{ --opacity-500ms-ease-in-out: opacity 500ms ease-in-out; }");a.appendToCSS(":root","{ --transform-500ms-ease: transform 500ms ease; }");
window.dispatchEvent(new Event("innerFunctionFinished"))},0)};isObject=function(a){return"object"===typeof a&&!Array.isArray(a)&&null!==a};isSafari=function(){var a=["Safari"];var b=function(c){return a.includes(c.brand)};return navigator.userAgentData?0<navigator.userAgentData.brands.filter(b).length:/^((?!chrome|android).)*safari/i.test(navigator.userAgent)};kebobCaseToCamelCase=function(a){return a[0].toLowerCase()+a.replace(/-(.)/g,function(b,c){return c.toUpperCase()}).slice(1)};
loadLocalResource=function(){function a(b){return function(c,d){return new Promise(function(e,g){var f="src";var l="body";var k=document.createDocumentFragment();var h=document.createElement(b);k.appendChild(h);h.onload=function(){e(c)};h.onerror=function(){g(c)};switch(b){case "script":h.async=!0;h.class="dynamic-script";break;case "link":h.type="text/css",h.rel="stylesheet",f="href",l="head"}Object.entries(d).forEach(function(n){var m=$jscomp.makeIterator(n);n=m.next().value;m=m.next().value;"async"!==
n||"true"!==m&&"false"!==m||(m=JSON.parse(m));h.setAttribute(n,m)});h[f]=tmbTT.active?tmbTT.policy.createScriptURL(c):c;document[l].appendChild(k)})}}return{css:a("link"),img:a("img"),js:a("script")}}();
loadPageDependencies=function(){var a;var b=!1;var c=this;if(c.siteData.hasOwnProperty("pageDependencies")&&c.siteData.pageDependencies.hasOwnProperty(c.pageName)){var d=c.siteData.pageDependencies[c.pageName];"object"===typeof d&&null!==d&&0!==Object.keys(d).length&&!1===c.loadedDependencies[c.pageName]&&d.hasOwnProperty("mjs")&&"string"===typeof d.mjs&&(b=!0,import(d.mjs).then(function(e){var g=[],f=[],l=[],k=[];c.assignToModulePropertyOnCommonObject(c.pageNameCamelCase,e.default);d.promiseLoader&&
Array.isArray(d.promiseLoader)&&0!==d.promiseLoader.length?(d.promiseLoader.forEach(function(h){var n=h[0],m=h[1];h=h[2];a=function(){c.hasOwnProperty("external")||(c.external={});c.external[n]=window[n];c[n]=window[n]};g.push(n);f.push(m);l.push(h);k.push(a)}),c.promiseLoader(g,f,l,k)):c.inner();c.loadedDependencies[c.pageName]=!0}).catch(function(e){console.log(e)}))}!1===b&&c.inner()};
makeTransparentMaskClickable=function(){var a=document.querySelector(".header .transparent-mask");var b=function(){document.querySelectorAll("#hamburger").forEach(function(c){c.click()})};a&&!a.classList.contains("transparent-mask-click-listener")&&(a.classList.add("transparent-mask-click-listener"),a.addEventListener("click",b,!1))};maxWidth759px=!0;
noTitle=function(a){var b=function(d){d.target.hasAttribute("title")&&(d.target.dataset&&!d.target.dataset.title&&(d.target.dataset.title=d.target.getAttribute("title")),d.target.setAttribute("title",""))};var c=function(d){d.target.dataset&&d.target.dataset.title&&d.target.setAttribute("title",d.target.dataset.title)};document.querySelectorAll(this.escapeForwardSlashes(a)).forEach(function(d){d.classList.contains("mouseover-listener")||(d.classList.add("mouseover-listener"),d.addEventListener("mouseover",
b));d.classList.contains("mouseout-listener")||(d.classList.add("mouseout-listener"),d.addEventListener("mouseout",c))})};popstateListener=function(){var a=this;window.addEventListener("popstate",function(){a.revealHashedContent("")},!1)};
promiseLoader=function(a,b,c,d){var e=this;var g=[];var f=[];var l=function(k){return window.hasOwnProperty(k)};a.forEach(function(k,h){window.hasOwnProperty(k)||(g.push(k),f.push(e.loadLocalResource.js(b[h],c[h])))});0!==f.length?Promise.all(f).then(function(){g.every(l)&&(d.forEach(function(k){k()}),e.inner(),g.forEach(function(k){console.log("Success: "+k+" loaded")}))}).catch(function(){g.forEach(function(k){console.log("Failure: "+k+" not loaded")})}):e.inner()};
returnAjaxObject=function(){var a=this;a.ajax={};a.ajax.post=function(b,c,d,e){var g=[];Object.keys(c).forEach(function(f){g.push(encodeURIComponent(f)+"="+encodeURIComponent(c[f]))});a.ajax.send(b,d,"POST",g.join("&"),e)};a.ajax.send=function(b,c,d,e,g){var f=new XMLHttpRequest;f.open(d,b,void 0===g?!0:g);f.onreadystatechange=function(){4===f.readyState&&(200===f.status?c(f.responseText):window.dispatchEvent(new Event("http404")))};"POST"===d&&f.setRequestHeader("Content-type","application/x-www-form-urlencoded");
f.send(e)};return a.ajax};returnTimeStamp=function(){var a=new Date;var b=a.getFullYear();var c=a.getMonth()+1;9>=c&&(c="0"+c);var d=a.getDate();var e=a.getHours();var g=a.getMinutes();a=a.getSeconds();return b+c+d+e+g+a};
revealHashedContent=function(a){var b;var c=this;var d=c.fenestra.location.href.substring(c.baseHref.length);"/"===d.slice(-1)&&(d=d.slice(0,-1));a=c.fenestra.location.href;c.targetURL=c.fenestra.location.origin+c.fenestra.location.pathname;c.previousURL!==c.targetURL&&c.ajaxMainContent(d,a,!0,"click");window.requestAnimationFrame(function(){window.scroll(0,0);d&&"#"===d.charAt(0)&&"#"!==d&&(b=document.querySelector(c.escapeForwardSlashes(d)),null!==b&&(b.scrollIntoView(),c.scrollDownByHeaderHeight()))})};
reviseSchema=function(){document.querySelectorAll("#schema-web-page").forEach(function(a){var b=JSON.parse(a.innerText);document.querySelectorAll('meta[name="description"]').forEach(function(c){b.description=c.getAttribute("content")});b.url=window.location.href;a.innerHTML=JSON.stringify(b)});document.querySelectorAll("#schema-person").forEach(function(a){var b=JSON.parse(a.innerText);b.url=window.location.href;a.innerHTML=JSON.stringify(b)})};
reviseMetaData=function(a){var b,c,d;var e=this;document.querySelectorAll("BASE").forEach(function(g){g.hasAttribute("href")&&(b=g.href)});document.querySelectorAll("LINK").forEach(function(g){g.hasAttribute("rel")&&"canonical"===g.rel&&g.hasAttribute("href")&&(c=g.href)});Object.entries(a).forEach(function(g){g=$jscomp.makeIterator(g);var f=g.next().value;g=g.next().value;e.isObject(g)&&Object.entries(g).forEach(function(l){l=$jscomp.makeIterator(l);var k=l.next().value,h=l.next().value;document.querySelectorAll("meta["+
f+'="'+k+'"]').forEach(function(n){a.page&&(d=a.page,n.dataset.page&&n.dataset.page===d||(h=h.replace("${BASE}",b),h=h.replace("${CANONICAL}",c),h=h.replace("${TITLE}",document.title),"${DEFAULT}"!==h&&(n.setAttribute("content",h),n.dataset.page=d)))})})});e.reviseSchema()};scrollDownByHeaderHeight=function(){var a=this;window.setTimeout(function(){window.scrollBy(0,-1*a.headerHeight)},500)};
serviceWorkerRoutine=function(){var a="19990221125549";this.metaNameWebAuthor&&this.metaNameWebAuthor.dataset&&this.metaNameWebAuthor.dataset.timestamp&&(a=this.metaNameWebAuthor.dataset.timestamp);if(void 0===navigator.serviceWorker)console.log("Service Worker not supported");else if(window.caches&&(window.caches.keys().then(function(c){return Promise.all(c.map(function(d){var e=parseInt(d.substring(0,14),10),g=parseInt(a.substring(0,14),10);e<g&&window.caches.delete(d).then(function(){console.log("cache "+
d+" is deleted")}).catch(function(f){console.log(f);return!1})})).catch(function(d){console.log(d);return!1})}).catch(function(c){console.log(c);return!1}),navigator.onLine)){console.log("Registering new Service Worker...");var b=tmbTT.active?tmbTT.policy.createScriptURL("sw.min.20220923054355.js"):"sw.min.20220923054355.js";navigator.serviceWorker.register(b,{scope:"./",updateViaCache:"none"}).then(function(c){c.update();console.log("New Service Worker registration successful with scope: ",c.scope);
console.log("Hard refresh at any time for new Service Worker.")}).catch(function(c){console.log("New Service Worker registration failed:",c)})}};setCanonicalLink=function(a){var b;if(b=document.querySelector('link[rel="canonical"]'))b.setAttribute("href",a);else{b=document.head.querySelectorAll("LINK");b=b[0];var c=document.createDocumentFragment();var d=document.createElement("LINK");c.appendChild(d);d.setAttribute("rel","canonical");d.setAttribute("href",a);b.parentNode.insertBefore(c,b.nextSibling)}};
setMaxWidth759px=function(){var a=this;var b=window.matchMedia("(max-width: 759px)");var c=function(d){a.maxWidth759px=d.matches?!0:!1};a.maxWidth759px=b.matches;Object.getPrototypeOf(b).addEventListener?b.addEventListener("change",c):b.addListener(c)};
setOrRemoveMobileClasses=function(){this.maxWidth759px?(this.anchorHashFragmentIntercept(),document.querySelectorAll(".menu-side-one").forEach(function(a){a.tabIndex=0}),document.querySelectorAll(".menu-side-two").forEach(function(a){a.tabIndex=-1})):(this.anchorHashFragmentIntercept(),document.querySelectorAll(".menu-side-one").forEach(function(a){a.tabIndex=0}),document.querySelectorAll(".menu-side-two").forEach(function(a){a.tabIndex=0}))};
setOrientation=function(){switch(window.orientation){case 0:document.body.dataset.orientation="portrait";this.onResizeEdits();break;case 90:document.body.dataset.orientation="landscape-left";this.onResizeEdits();break;case -90:document.body.dataset.orientation="landscape-right",this.onResizeEdits()}};
siteWideLoader=function(){function a(){document.querySelectorAll(".dynamic-script").forEach(function(e){e.parentNode.removeChild(e)})}function b(){var e=d.shift(),g=document.createDocumentFragment(),f=document.createElement("script"),l;g.appendChild(f);Object.keys(e).forEach(function(k){l=e[k];f[k]=tmbTT.active&&"src"===k?tmbTT.policy.createScriptURL(l):l;"data"===k.substring(0,4)&&f.setAttribute(c.camelCaseToKebobCase(k),e[k])});void 0===f.type&&(f.type="text/javascript");c.nonce&&f.setAttribute("nonce",
c.nonce);f.async=!1;f.classList.add("dynamic-script");0<d.length&&"text/javascript"===f.type&&(f.onload=b,f.onerror=function(k){console.log(f.src+" could not load:");console.log(k);b()});document.body.appendChild(g);0<d.length&&"text/javascript"!==f.type?b():a()}var c=this;c.isMobile=navigator.userAgentData?navigator.userAgentData.mobile:/iPhone|iPad|iPod|Android/i.test(navigator.userAgent);var d=[];(function(){function e(k){for(var h=[];null!==k.nextElementSibling;)h.push(k.nextElementSibling),k=
k.nextElementSibling;return h}function g(k){return"SCRIPT"===k.nodeName&&k.hasAttribute("type")&&"application/ld+json"===k.getAttribute("type")}function f(k,h){var n=e(k);Object.keys(n).forEach(function(m){m=n[m];h(m)||m.parentNode.removeChild(m)})}var l=document.querySelector("footer");null!==l&&f(l,g)})();0!==d.length&&b()};stripHtmlTags=function(a){return(new DOMParser).parseFromString(a,"text/html").body.textContent||""};tmbTT={};
updateFenestra=function(){var a=document.body.hasAttribute("data-admin");var b=this.metaNameWebAuthor&&this.metaNameWebAuthor.dataset&&this.metaNameWebAuthor.dataset.chromeLighthouse;var c=this.siteData&&this.siteData.liveSiteUrl&&window.location.origin===this.siteData.liveSiteUrl;!a&&!b&&c&&navigator.onLine&&this.googleAnalyticsInitialized&&this.gtag&&!0!==this.inEu&&(a={anonymize_ip:!0,cookie_flags:"SameSite=None; Secure",page_path:window.location.pathname,send:"pageview"},this.gtag("config",this.siteData.uaString,
a));this.fenestra={};this.fenestra.location={};this.fenestra.location.hash=window.location.hash;this.fenestra.location.href=window.location.href;-1<this.fenestra.location.href.indexOf("?")&&(this.fenestra.location.href=this.fenestra.location.href.split("?")[0]);this.fenestra.location.origin=window.location.origin;this.fenestra.location.pathname=window.location.pathname};updateUriInfo=function(){this.previousURL=this.fenestra.location.origin+this.fenestra.location.pathname};
windowEvents={hashchange:!1,keydown:!1,load:!1,popstate:!1,resize1:!1,resize2:!1};export default Object.freeze({activateLoadingMask, ajaxMainContent, anchorHashFragmentIntercept, anchorIntercept, aspectRatioImgEdits, calledCommonVariables, camelCaseToKebobCase, checkTrustedTypesSupport, closeDrawerOnAnchorClick, commonEventListeners, commonRoutines, commonRoutinesOnFirstLoadOnly, commonRoutinesOnFirstLoadOrAjax, commonVariables, conditionallyReplaceJpgExtensionWithWebpExtension, consoleLog, consoleLogMsgObj, customizePushAndReplaceState, deactivateLoadingMask, deleteCachesUnregisterServiceWorkerAndClearSessionStorage, editExternalLinks, escapeForwardSlashes, escapeSingleQuotes, fetchAppendToUploadStatusDiv, fetchReject, fetchResolve, fetchResolveWithOptions, fetchResponse, fireCustomEvent, fiveRandomAlphaNumerics, highlightMenuItem, inEu, initializeHeaderHeightAndObserver, initializePopstateLocationChangeListeners, initializeWindowOnResizeRoutines, inner, isObject, isSafari, kebobCaseToCamelCase, loadLocalResource, loadPageDependencies, makeTransparentMaskClickable, maxWidth759px, noTitle, popstateListener, promiseLoader, removeVisibilityHiddenFromTmbAlert, returnAjaxObject, returnTimeStamp, revealHashedContent, reviseMetaData, reviseSchema, scrollDownByHeaderHeight, serviceWorkerRoutine, setMaxWidth759px, setCanonicalLink, setOrRemoveMobileClasses, setOrientation, siteWideLoader, stripHtmlTags, tmbTT, updateFenestra, updateUriInfo, windowEvents}); 
